### ISSUE TITLE
add composer.json

### ISSUE THREAD

**Issue by kaystrobach** [PHPOffice/PhpProject#9]

**Comment by kaystrobach** [comment]
![image](https://f.cloud.github.com/assets/1185776/1326881/21f7236e-34e6-11e3-9c4f-e0dbac8abe04.png)

**Comment by Progi1984** [comment]
PHPProject is now available on Packagist : https://packagist.org/packages/phpoffice/phpproject

**Comment by kaystrobach** [comment]
thank you
